### ISSUE TITLE
Not able to detect all the duplicate images

### ISSUE THREAD

**Issue by royinblr** [erdogant/undouble#2]
![NOVA-NA-Dry-Iron-Grey-SDL881739255-1-3a886](https://user-images.githubusercontent.com/21307959/165252701-43e65042-abb5-464d-bf97-cfa8daa22acf.jpeg)
![nova-plus-1100-w-amaze-ni-10-original-imaf3qxpabhhdwss](https://user-images.githubusercontent.com/21307959/165252712-43e1a91f-3be0-4ffa-86b2-e3c18dc3add5.jpeg)
![philips-hi113-hi113-original-imafkmkfuwuafnpf](https://user-images.githubusercontent.com/21307959/165252715-df95be0e-f987-491f-be9e-5bc862b157c7.jpeg)
![philips-hl114-1000-w-dry-iron-500x500](https://user-images.githubusercontent.com/21307959/165252717-f4748144-0ed3-4d3c-b8dd-9c2e2faa45e7.png)
![deson](https://user-images.githubusercontent.com/21307959/165252721-d734174b-b5f6-4768-aa82-0ffd13d05f70.png)
![deson-copy](https://user-images.githubusercontent.com/21307959/165252723-407ba7ca-4df1-43d2-8fec-4bb82dfb6a35.png)
![deson-steam-iron-250x250](https://user-images.githubusercontent.com/21307959/165252728-9d5f707f-3f39-494c-a8fd-3638f024fda7.jpg)
![deson-steam-iron-500x500](https://user-images.githubusercontent.com/21307959/165252730-559901e7-b7d3-44d6-8bea-16433c0bc566.jpg)
![ki735](https://user-images.githubusercontent.com/21307959/165252731-9540b65b-d649-4cce-bfa7-b3c7e34469ef.jpg)
![ki7352](https://user-images.githubusercontent.com/21307959/165252736-6d620f8c-7950-45b4-bfe6-7899cb940805.jpg)
Not all the duplicates are detected.

**Comment by erdogant** [comment]
With `model.compute_hash(method='phash', hash_size=16)` I was able to detect some duplicates but it seems that certain images require some pre-processing because a black or white border is present. This makes a huge difference in the hash. 

Example:
![image](https://user-images.githubusercontent.com/31008129/167497751-802de18b-42d3-453f-a0b3-25e86e01f714.png)

**Comment by erdogant** [comment]
send me a pm if you want this functionality to be added, and we can discuss what's possible.
