### ISSUE TITLE
import_data from http image_url

### ISSUE THREAD

**Issue by jomosi** [erdogant/undouble#3]
model = Undouble(method='phash', hash_size=8)
targetdir = [
'https://www.gardendesign.com/pictures/images/675x529Max/site_3/helianthus-yellow-flower-pixabay_11863.jpg'
]
model.import_data(targetdir)
model.compute_hash()

could you add a new feature of importing data directly from http image url not using downloading ono disk.

Thank you.

**Comment by erdogant** [comment]
Good suggestion. Reading from url location is implemented now.
Checkout the documentation over [here](https://erdogant.github.io/undouble/pages/html/Examples.html#import-images-from-url-location)
