### ISSUE TITLE
/tmp folder clean up needed

### ISSUE THREAD

**Issue by jomosi** [erdogant/undouble#4]
Hello,

I have found some kind of bug in undouble lib.

After using undouble lib. many times like millions, tons of empty temporary folders are made in /tmp (in linux) and never removed. 
It leads to system fail because of lack of free inode (in linux).

It is because of "tempfile.mkdtemp()" in your source code from clustimage.py.

I think you have to remove temp folder in destructor in the class.

Thanks.

**Comment by erdogant** [comment]
Thank you for this good suggestion and created some changes in the new version.

* The temp directory is not a random new dirname anymore but is "clustimage" in the systems temp directory.
* Files for the specific run can easily be removed using the `.clean_files()` functionality.
* The entire temp directory can removed setting the parameter `.clean_files(clean_tempdir=True)`.

**Comment by erdogant** [comment]
Let me know and/or re-open if this issue if required.
