### ISSUE TITLE
simple mistake found in undouble.py

### ISSUE THREAD

**Issue by jomosi** [erdogant/undouble#6]
def compute_hash(self, method=None, hash_size=None, return_dict=False):

....

        if method=='whash-haar':
            if (np.ceil(np.log2(hash_size)) != np.floor(np.log2(hash_size))):
                logger.error('hash_size should be power of 2 (8, 16, 32, 64, ..., etc)')
                return None

Default value for hash_size (None) is passed to np.log2(hash_size) when hash_size is not given.

**Comment by erdogant** [comment]
Thanks for mentioning it! I set the default to 8 and created a new release (>= v1.2.9).

**Comment by erdogant** [comment]
I am closing this issue. Reopen if required.
